doctrine:
    orm:
        auto_mapping: true
        # the standard distribution overrides this to be true in debug, false otherwise
        auto_generate_proxy_classes: false
        proxy_namespace: Proxies
        proxy_dir: "%kernel.cache_dir%/doctrine/orm/Proxies"
        default_entity_manager: default
        mappings:
            default_mapping:
                type: annotation
                prefix: App\Entity\
                dir: "%kernel.root_dir%/Entity/"
                is_bundle: false
            custom_mapping:
                type: annotation
                prefix: App\Entity\Dictionary\
                dir: "%kernel.root_dir%/Entity/Dictionary/"
                is_bundle: false
        dql:
            string_functions:
                MATCH_AGAINST: App\Extensions\Doctrine\MatchAgainst
    dbal:
        url: '%env(DATABASE_URL)%'
        charset: UTF8
        server_version: '5.7'
