language: php

php:
  - '7.1'

services:
  - mysql

cache:
  directories:
    - $HOME/.composer

before_install:
  - phpenv config-rm xdebug.ini
  - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
  - echo "memory_limit=1G" >> $INI_FILE;
  - echo 'date.timezone = "Europe/Istanbul"' >> $INI_FILE;

before_script:
  - php bin/console doctrine:schema:create --env=test
  - composer self-update
  - composer install
  - php bin/console doctrine:migrations:migrate --no-interaction --env=test
  - php bin/console doctrine:fixtures:load --no-interaction --env=test

script:
  - php bin/console lint:yaml config/
  - php vendor/phpunit/phpunit/phpunit -c app src/
