language: php

php:
  - '7.1'

env:
  - SYMFONY_DEPRECATIONS_HELPER=max[self]=0

services:
  - mysql

cache:
  directories:
    - $HOME/.composer

before_install:
  - phpenv config-rm xdebug.ini
  - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
  - echo "memory_limit=256M" >> $INI_FILE;
  - echo 'date.timezone = "Asia/Baku"' >> $INI_FILE;

install:
  - composer self-update
  - composer install
  - composer global require friendsofphp/php-cs-fixer
  - export PATH="$PATH:$HOME/.composer/vendor/bin"

before_script:
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:migrations:migrate --no-interaction --env=test
  - php bin/console doctrine:fixtures:load --no-interaction --env=test

script:
  - php bin/console lint:yaml config/
  - php bin/console doctrine:schema:validate
  - php bin/phpunit
  - php vendor/bin/psalm
  - php-cs-fixer fix --config=.php_cs.dist -v --dry-run

notifications:
  email: false
